### ISSUE TITLE
here package in Stegen

### ISSUE THREAD

**Issue by aspina7** [reconhub/learn#56]
worth noting in stegen that there are other packages with a "here" function. 
E.g. people later loaded dplyr and lubridate after here, so then couldnt use here::here. 
Maybe worth adding a note on semicolon use.... ?

**Comment by zkamvar** [comment]
Hi, Sorry for not getting to this until now. I've been on leave on the other side of the world. It's worth noting that the culprit is lubridate specifically:

``` r
lubridate::here
#> function () 
#> {
#>     .deprecated_fun("now", "1.5.6")
#>     now()
#> }
#> <bytecode: 0x7faf8e16e7b0>
#> <environment: namespace:lubridate>
dplyr::here
#> Error: 'here' is not an exported object from 'namespace:dplyr'
```

<sup>Created on 2019-01-07 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

I think it's absolutely worth it to use `here::here()` in this instance and include a little explainer box. Besides, it gives us an opportunity to say that we are using it as a way to give a little cheer for R 😝.

**Comment by aspina7** [comment]
@nsbatra this was the conflict with {here} - {lubridate} has too
